version: '3'

tasks:
  build:
    cmds:
      - dotnet build Dojo.Net.sln -c Debug
  release:
    cmds:
      - dotnet build Dojo.Net.sln -c Release
  run:
    cmds:
      - cd Dojo.Net/bin/Debug && dotnet Dojo.Net.dll
  bench:
    cmds:
      - cd Dojo.Net/bin/Release && dotnet Dojo.Net.dll
  test:
    cmds:
      - dotnet test Dojo.Net.sln